### ISSUE TITLE
你好，学习中遇到问题，向你请教

### ISSUE THREAD

**Issue by huangchengshengqishi** [BlackFlagBin/SemiCircleProgress#1]
我在Android studio3.3.2中打开项目编译时遇到下面的错误提示，请问怎样解决，我是小白，谢谢解答

ERROR: The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.0 and higher.
The following dependencies do not satisfy the required version:
root project 'SemiCircleProgress-master' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.0
Affected Modules: app

**Comment by BlackFlagBin** [comment]
kotlin版本太低了，把依赖版本改到1.3.0以上就ok了

**Comment by BlackFlagBin** [comment]
kotlin版本太低了，你改到1.3.0以上就ok了

**Comment by huangchengshengqishi** [comment]
![image](https://user-images.githubusercontent.com/28882284/55126495-2ca4be00-5148-11e9-981d-84529286c17c.png)
kotlin版本目前是1.3.21，错误提示依然存在，实在搞不懂是为什么？当前Androidstudio版本是3.3.2
